### ISSUE TITLE
Setting hide=true no longer works

### ISSUE THREAD

**Issue by jpadilla** [knownasilya/pagination-pager#25]
Seems like setting `hide=true` on pagination-pager no longer seems to hide the component if `count=1`

**Comment by jpadilla** [comment]
Further more, [isHidden](https://github.com/knownasilya/pagination-pager/blob/cb948ad1affb1cfbed47c0103cac07212cbe3b55/addon/components/pagination-pager.js#L84) doesn't seem to be used anywhere.

**Comment by knownasilya** [comment]
Thanks for submitting this :+1: I need to write tests..

**Comment by knownasilya** [comment]
So `isHidden` is used here: https://github.com/knownasilya/pagination-pager/blob/master/addon/components/pagination-pager.js#L8

**Comment by knownasilya** [comment]
Should be working now, I also made it check if count is falsy. There is also now an `autoHide` option, which can be toggled off. Basically if you toggle it off, then `hide` just works like wrapping the component in an `{{#if ..}}`.

**Comment by jpadilla** [comment]
@knownasilya great, thanks for the quick resolution!
