### ISSUE TITLE
Block-based pagination does not show current and count

### ISSUE THREAD

**Issue by andorfermichael** [knownasilya/pagination-pager#31]
I tried to implement the following example:

```
{{#pagination-pager count=5 current=2 pager=true}}
    Page {{current}} of {{count}}
{{/pagination-pager}}
```

`previous` and `next `are working fine but `current` and `count` are not working at all.

Output:
previous Page of next

**Comment by knownasilya** [comment]
No that wouldn't work, since you don't have them defined as attributes. The following should work.

```hbs
{{#pagination-pager count=count current=current pager=true}}
    Page {{current}} of {{count}}
{{/pagination-pager}}
```

Where `count` and `current` are defined in your controller or parent component.

**Comment by andorfermichael** [comment]
Ah, I understand but maybe this is kind of an issue of documentation then.

**Comment by knownasilya** [comment]
I've updated the block example. Thanks!

**Comment by andorfermichael** [comment]
Thank you too for the quick response and reaction!
