### ISSUE TITLE
`autoHide=false` and `count=1` 

### ISSUE THREAD

**Issue by miguelcobain** [knownasilya/pagination-pager#32]
Seems that using `autoHide=false` and `count=1` hides the pager.
Is this expected?

**Comment by knownasilya** [comment]
It is, but if you think it doesn't make sense we can revise.

**Comment by miguelcobain** [comment]
In the docs we can read
> autoHide -- Hide the component if count is <= 1, defaults to true.

So I expect if `autoHide` is false, the negative sentence applies:
"**Don't** hide the component if count is <= 1".

My expectation was that `autoHide=false` would disable any`autoHide` functionality.

**Comment by knownasilya** [comment]
Ah, yes you are correct, that is how it should work, and it should just work https://github.com/knownasilya/pagination-pager/blob/master/addon/components/pagination-pager.js#L96

**Comment by miguelcobain** [comment]
That gets transpiled to

```js
return hide || autoHide && !count || count <= 1;
```

This evaluates to true if `hide` and `autoHide` are false and `count` is `1`.

**Comment by knownasilya** [comment]
Give the master dummy app a try, it seems to work fine in the autohide example.

**Comment by knownasilya** [comment]
Ah, this was resolved with #30, but I forgot to publish. Published as v2.4.2
