### ISSUE TITLE
Update bootstrap version

### ISSUE THREAD

**Issue by ValentinTrinque** [knownasilya/pagination-pager#34]

**Comment by knownasilya** [comment]
To 4? it's still in alpha, but feel free to submit a PR, I can start a branch.

**Comment by ValentinTrinque** [comment]
Hi, Sorry I created an issue like a brute, I could have write something... ^^"

No I was thinking about updating to bootstrap 3.3.5. There are some (minor) fixes on the pagination.

**Comment by knownasilya** [comment]
I dont actually bundle bootstrap with this addon, so as long as the html is the same no changes should be necessary. Are you seeing issues?

**Comment by ValentinTrinque** [comment]
Some changes occurs for accessibility purpose, mainly, but that doesn't require _actual_ HTML changes, expect wrapping the pagination inside a `<nav>` and add `aria-label`. So I guess I've mistaken.

**Comment by knownasilya** [comment]
I mean, that might actually be worth doing.

**Comment by ValentinTrinque** [comment]
Do you want to take care of it ?

**Comment by knownasilya** [comment]
Yeah, I've started on the change, will release the new version this week.

**Comment by ValentinTrinque** [comment]
Very nice !
