### ISSUE TITLE
Deprecation warning "no JavaScript preprocessors were found"

### ISSUE THREAD

**Issue by simonc** [knownasilya/pagination-pager#35]
Hello,

I started a new project using Ember v2.12 and have the following warning:

> DEPRECATION: Addon files were detected in `/Users/simonc/Documents/Tinci/Projects/LeCollectionist/customer-advising-dashboard/node_modules/pagination-pager/addon`, but no JavaScript preprocessors were found for `pagination-pager`. Please make sure to add a preprocessor (most likely `ember-cli-babel`) to in `dependencies` (NOT `devDependencies`) in `pagination-pager`'s `package.json`.

Thought you'd want to know :wink:

Cheers,

**Comment by knownasilya** [comment]
Thanks!

**Comment by jpadilla** [comment]
Fixed by #36

**Comment by simonc** [comment]
❤️
