### ISSUE TITLE
The UI style change to my native design ?

### ISSUE THREAD

**Issue by terrycafe520** [knownasilya/pagination-pager#39]
This UI component is very helpful .  Thank you !
My question is how can I  change the UI css style . We use this component every route. But it's css style is not PM wanted . 
So I tried to find your code in my project , But Not Found . 
I install it followed the document .
So how can I change the css classname ?

**Comment by knownasilya** [comment]
You can extend the component like so

```js
// app/components/my-pagination.js
import paginationPagerComponent from 'pagination-pager/components/pagination-pager';

export default PaginationPagerComponent.extend({
  classNames: ['my-class']
});
```

and use with `{{my-pagination ...}}`.
