### ISSUE TITLE
Dynamic variables completely break this plugin

### ISSUE THREAD

**Issue by billybonks** [knownasilya/pagination-pager#9]
i forked and modified your dummy app to show how dynamic variables break this plugin completely, i believe it should support this

https://github.com/Limitliss/pagination-pager

**Comment by knownasilya** [comment]
I don't see any changes on that fork..

**Comment by billybonks** [comment]
sorry forgot to commit, check again

**Comment by knownasilya** [comment]
Still nothing, did you forget to push it up?

**Comment by billybonks** [comment]
ye, sorry should be good now

**Comment by knownasilya** [comment]
@billybonks can you explain exactly what breaks and what you're trying to do?

**Comment by billybonks** [comment]
basically i have a list of 2000 elements, this list then gets filtered. as it gets filtered i change the count value to match the new page count, and reset the current to 1.

if i use the numbered pager the it shows to little pages like 2 instead of 5, and you can go next up to the original element count. 

if you try change the values in the input boxes, in the example i prepared you will see the pagination components break

**Comment by knownasilya** [comment]
You set the value of `current` to `0`, when `firstPage` is set to `1`. Looks like a bug, but you can get around it by setting `firstPage=0`.

**Comment by billybonks** [comment]
besides the first value, if you try change the page count it breaks aswell

**Comment by knownasilya** [comment]
@billybonks could you see if the current version still has this same issue?

**Comment by knownasilya** [comment]
@billybonks check out the demo page for an example. The fix has been released as v2.3.1.

**Comment by billybonks** [comment]
thanks :)

On Tue, Nov 3, 2015 at 10:18 PM, Ilya Radchenko <notifications@github.com>
wrote:

> @billybonks <https://github.com/billybonks> check out the demo page for
> an example. The fix has been released as v2.3.1.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/knownasilya/pagination-pager/issues/9#issuecomment-153368620>
> .
>



-- 
Kind Regards
Sebastien Stettler

**Comment by knownasilya** [comment]
@billybonks it only took 9 months lol :smile_cat:
